local GameConfig = {}

GameConfig.DATA_STORE_NAME = "MonsterFactory_PlayerData_v1"
GameConfig.DATA_VERSION = 4

GameConfig.STARTING_CASH = 100
GameConfig.STARTING_GEMS = 25
GameConfig.STARTING_REBIRTH_TOKENS = 0

GameConfig.BASE_PRODUCTION_PER_SECOND = 10
GameConfig.UPGRADE_BASE_COST = 50
GameConfig.UPGRADE_COST_GROWTH = 1.65
GameConfig.UPGRADE_PRODUCTION_GROWTH = 1.28

GameConfig.BASE_EQUIP_SLOTS = 3
GameConfig.BASE_STORAGE = 50

GameConfig.CAPSULE_HATCH_COOLDOWN = 0.35
GameConfig.REMOTE_RATE_LIMIT_SECONDS = 0.12
GameConfig.SAVE_INTERVAL_SECONDS = 60

GameConfig.SHINY_REQUIRED_DUPLICATES = 5
GameConfig.SHINY_POWER_MULTIPLIER = 2.5

GameConfig.REBIRTH_BASE_REQUIREMENT = 3000000
GameConfig.REBIRTH_REQUIREMENT_GROWTH = 7
GameConfig.REBIRTH_PRODUCTION_BONUS = 0.50

GameConfig.DAILY_CLAIM_COOLDOWN_SECONDS = 20 * 60 * 60

GameConfig.OFFLINE_MAX_SECONDS = 8 * 60 * 60
GameConfig.OFFLINE_BASE_EFFICIENCY = 0.25
GameConfig.OFFLINE_VIP_EFFICIENCY_BONUS = 0.10

GameConfig.FRIEND_BONUS_PER_FRIEND = 0.05
GameConfig.FRIEND_BONUS_MAX = 0.20

GameConfig.CONTEXT_OFFER_COOLDOWN_SECONDS = 12 * 60

return GameConfig
